"""``pyproject.toml`` 的 ruff 配置钉住用例。

两张清单只许变短，不许变长：

1. ``[tool.ruff.lint.per-file-ignores]``——存量 ``D``（docstring 结构）/
   ``PLR0913``（参数个数）以及门禁接线批留下的 ``I001``/``UP035``/``F401``/
   ``N818``/``N802`` 残留登记表。后续清理批会逐个文件把条目删空或缩短，收官
   目标是整张表清空。
2. ``[tool.ruff.format].exclude``——门禁接线批刻意不写这一节，全仓格式化留给
   后续批次；因此这里钉住的是**空集**，那个批次接线时需要同步把这条测试的
   钉住清单换成它实际写入的排除列表（那是它自己的收口职责，不是本测试要提前
   预留的空子）。

判定方式是子集，不是逐字相等：允许某个文件的条目从表里整条删除，也允许某个文件
保留的规则码变少；唯一不允许的是**出现新文件**或**某个已登记文件出现新规则码**
——那意味着有人往清单里"加"而不是"减"，与本表"只收紧"的设计意图相反。

变异实测：临时在 ``pyproject.toml`` 的 per-file-ignores 里给任意一个已登记文件
追加一个此前没有的规则码，或新增一个此前未登记的文件条目，跑本文件应判红；
改完验证后删除该临时改动、清 ``__pycache__``。
"""

from __future__ import annotations

import tomllib
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).parents[1]
PYPROJECT = REPO_ROOT / "pyproject.toml"


def _load_ruff_config() -> dict:
    with PYPROJECT.open("rb") as handle:
        document = tomllib.load(handle)
    return document["tool"]["ruff"]


# 以下常量是接线落地时 pyproject.toml 里 [tool.ruff.lint.per-file-ignores] 的
# 逐字快照，按文件路径排序。后续清理批缩短实际清单后，无需同步缩短这份钉住
# 快照——测试断言的是"实际 ⊆ 钉住"，钉住快照只是历史上限，不用跟着每次收紧
# 同步下调（除非要收紧钉住本身，那是一次有意的门禁升级，不属于批次清理的日常
# 工作）。
PINNED_PER_FILE_IGNORES: dict[str, frozenset[str]] = {
    "migrations/alembic/env.py": frozenset(["D", "I001"]),
    "migrations/alembic/migration_dsn.py": frozenset(["D"]),
    "migrations/alembic/versions/0054_retention_cleanup.py": frozenset(["D"]),
    "migrations/alembic/versions/0057_gateway_tables.py": frozenset(["D"]),
    "migrations/alembic/versions/0058_worker_execution.py": frozenset(["D"]),
    "migrations/alembic/versions/0059_delivery_outbox.py": frozenset(["D"]),
    "migrations/alembic/versions/0060_gateway_delivery_dispatch.py": frozenset(["D"]),
    "migrations/alembic/versions/0061_agent_session_cleanup.py": frozenset(["D"]),
    "migrations/alembic/versions/0062_onboarding_dispatch_ledger.py": frozenset(["D"]),
    "migrations/alembic/versions/0063_roster_snapshot.py": frozenset(["D"]),
    "migrations/alembic/versions/0064_permission_publish_outbox.py": frozenset(["D"]),
    "migrations/alembic/versions/0065_mcp_token_and_sync_check.py": frozenset(["D"]),
    "migrations/alembic/versions/0066_onboarding_notice_outbox.py": frozenset(["D"]),
    "migrations/alembic/versions/0067_admin_registry.py": frozenset(["D"]),
    "migrations/alembic/versions/0068_pending_action.py": frozenset(["D"]),
    "migrations/alembic/versions/0069_innertest_content_capture.py": frozenset(["D"]),
    "migrations/alembic/versions/0070_task_report_metrics.py": frozenset(["D"]),
    "migrations/alembic/versions/0071_daily_report_watermark.py": frozenset(["D"]),
    "migrations/alembic/versions/0072_local_permission_override.py": frozenset(["D"]),
    "migrations/alembic/versions/0073_pending_action_perm_types.py": frozenset(["D"]),
    "migrations/alembic/versions/0074_task_document_delivery.py": frozenset(["D"]),
    "migrations/alembic/versions/0075_progress_event_content.py": frozenset(["D"]),
    "migrations/alembic/versions/0076_user_memory.py": frozenset(["D"]),
    "migrations/alembic/versions/0077_onboarding_failure_reason.py": frozenset(["D"]),
    "migrations/alembic/versions/0078_document_delivery_sheet.py": frozenset(["D"]),
    "migrations/alembic/versions/0079_document_delivery_markdown.py": frozenset(["D"]),
    "migrations/alembic/versions/0080_task_failure_signature.py": frozenset(["D"]),
    "migrations/alembic/versions/0081_management_card_context.py": frozenset(["D"]),
    "migrations/alembic/versions/0082_document_delivery_degraded.py": frozenset(["D"]),
    "migrations/alembic/versions/0083_management_card_recovery.py": frozenset(["D"]),
    "migrations/alembic/versions/0084_management_card_state_cas.py": frozenset(["D"]),
    "migrations/alembic/versions/0085_app_user_email_unique.py": frozenset(["D"]),
    "migrations/alembic/versions/0086_publish_outbox_digest.py": frozenset(["D"]),
    "migrations/alembic/versions/0087_preprovision_seams.py": frozenset(["D"]),
    "migrations/alembic/versions/20260806_baseline_006_012.py": frozenset(["D"]),
    "scripts/acceptance_fixtures.py": frozenset(["D"]),
    "scripts/acceptance_fixtures_identity.py": frozenset(["D"]),
    "scripts/ci/check_acceptance_matrix.py": frozenset(["D"]),
    "scripts/ci/check_agent_sdk_binding.py": frozenset(["D"]),
    "scripts/ci/check_alembic_revisions.py": frozenset(["D"]),
    "scripts/ci/check_content_version.py": frozenset(["D"]),
    "scripts/ci/check_contract_attribution.py": frozenset(["D"]),
    "scripts/ci/check_core_layering.py": frozenset(["D"]),
    "scripts/ci/check_crypto_vectors.py": frozenset(["D"]),
    "scripts/ci/check_db_timeouts.py": frozenset(["D"]),
    "scripts/ci/check_deploy_contract.py": frozenset(["D"]),
    "scripts/ci/check_docs_size_budget.py": frozenset(["D"]),
    "scripts/ci/check_installed_package.py": frozenset(["D"]),
    "scripts/ci/check_l1_assets.py": frozenset(["D"]),
    "scripts/ci/check_markdown_links.py": frozenset(["D"]),
    "scripts/ci/check_matrix_row_size_ratchet.py": frozenset(["D"]),
    "scripts/ci/check_permission_impact.py": frozenset(["D"]),
    "scripts/ci/check_project_skills.py": frozenset(["D"]),
    "scripts/ci/check_runtime_dependencies.py": frozenset(["D"]),
    "scripts/ci/check_size_ratchet.py": frozenset(["D"]),
    "scripts/ci/classify_story_changes.py": frozenset(["D"]),
    "scripts/ci/image_manifest.py": frozenset(["D"]),
    "scripts/ci/prepare_permission_impact_counts.py": frozenset(["D"]),
    "scripts/ci/push_image.py": frozenset(["D"]),
    "scripts/ci/verify_epic_candidate.py": frozenset(["D"]),
    "scripts/ci/verify_epic_candidate_bundle.py": frozenset(["D"]),
    "scripts/ci/write_epic_candidate.py": frozenset(["D"]),
    "scripts/ci/write_epic_candidate_images.py": frozenset(["D"]),
    "scripts/dev/gate_spec.py": frozenset(["D"]),
    "scripts/dev/local_layer.py": frozenset(["D"]),
    "scripts/import_galaxy_permission_export.py": frozenset(["D"]),
    "scripts/invalidate_pretranslation_publish_intents.py": frozenset(["D"]),
    "scripts/ops/export_permission_impact_counts.py": frozenset(["D"]),
    "scripts/ops/host_health_alert.py": frozenset(["D"]),
    "scripts/ops/import_local_permission_override.py": frozenset(["D", "F401"]),
    "scripts/ops/monitoring/_resource_sample.py": frozenset(["D"]),
    "scripts/ops/preprovision.py": frozenset(["D"]),
    "scripts/probe_drive_folder_permissions.py": frozenset(["D", "N818"]),
    "scripts/probe_message_reactions.py": frozenset(["D"]),
    "scripts/replay_inbound_event.py": frozenset(["D"]),
    "src/lingxi/adapters/admin_metric_alias_map_file.py": frozenset(["D"]),
    "src/lingxi/adapters/admin_post_callback.py": frozenset(["D"]),
    "src/lingxi/adapters/admin_registry.py": frozenset(["D"]),
    "src/lingxi/adapters/claude_agent_hooks.py": frozenset(["D"]),
    "src/lingxi/adapters/claude_agent_session.py": frozenset(["D", "PLR0913", "N818"]),
    "src/lingxi/adapters/company_function_metric_map_file.py": frozenset(["D"]),
    "src/lingxi/adapters/delegated_credentials.py": frozenset(["D"]),
    "src/lingxi/adapters/delegated_subject_lookup.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_admin_card.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_bitable_association.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_delivery.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_directory.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_docx_delivery.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_events.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_group_message.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_longconn.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_org_snapshot_reader.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_outbound.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_permission_bitable.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_reauthorization.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_roster_bitable.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_sheets_delivery.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_tenant_token.py": frozenset(["D"]),
    "src/lingxi/adapters/feishu_user_message.py": frozenset(["D"]),
    "src/lingxi/adapters/galaxy_csv_export.py": frozenset(["D"]),
    "src/lingxi/adapters/galaxy_import.py": frozenset(["D"]),
    "src/lingxi/adapters/mcp_token_cipher.py": frozenset(["D"]),
    "src/lingxi/adapters/oauth_bridge_client.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_content_capture.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_content_capture_retention.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_conversation/_dataclasses.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_conversation/_gateway_store.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_conversation/_listener.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_conversation/_queue_base.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_conversation/_queue_gateway_delivery.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_conversation/_queue_lifecycle.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_conversation/_queue_outbox.py": frozenset(["D", "PLR0913"]),
    "src/lingxi/adapters/postgres_conversation/_queue_session_cleanup.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_conversation/_task_queue.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_conversation/_transaction.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_daily_report.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_daily_report_watermark.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_document_delivery.py": frozenset(["D", "N818"]),
    "src/lingxi/adapters/postgres_email_binding.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_galaxy_snapshot.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_identity.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_late_readiness_recovery.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_local_permission.py": frozenset(["D", "PLR0913", "N818"]),
    "src/lingxi/adapters/postgres_management_card_context.py": frozenset(["D", "PLR0913"]),
    "src/lingxi/adapters/postgres_mcp_token.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_onboarding_failure.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_pending_action.py": frozenset(["D", "PLR0913"]),
    "src/lingxi/adapters/postgres_permission_publish.py": frozenset(["D", "N818"]),
    "src/lingxi/adapters/postgres_permission_recompute_trigger.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_roster_audit.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_roster_snapshot.py": frozenset(["D", "N818"]),
    "src/lingxi/adapters/postgres_stalled_provisioning.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_targeted_recompute_lookup.py": frozenset(["D"]),
    "src/lingxi/adapters/postgres_user_memory.py": frozenset(["D"]),
    "src/lingxi/adapters/query_mcp_probe.py": frozenset(["D"]),
    "src/lingxi/adapters/retention.py": frozenset(["D"]),
    "src/lingxi/adapters/role_function_map_file.py": frozenset(["D"]),
    "src/lingxi/adapters/stock_token_bitable.py": frozenset(["D"]),
    "src/lingxi/adapters/user_environment.py": frozenset(["D"]),
    "src/lingxi/adapters/user_mcp_config.py": frozenset(["D"]),
    "src/lingxi/apps/admin_bootstrap/__init__.py": frozenset(["D"]),
    "src/lingxi/apps/gateway/__init__.py": frozenset(["D", "I001", "UP035"]),
    "src/lingxi/apps/gateway/config.py": frozenset(["D"]),
    "src/lingxi/apps/gateway/delivery.py": frozenset(["D", "PLR0913"]),
    "src/lingxi/apps/gateway/document_delivery.py": frozenset(["D"]),
    "src/lingxi/apps/gateway/group_mention_hint.py": frozenset(["D"]),
    "src/lingxi/apps/gateway/log_redaction.py": frozenset(["D"]),
    "src/lingxi/apps/gateway/management_status.py": frozenset(["D"]),
    "src/lingxi/apps/gateway/onboarding.py": frozenset(["D"]),
    "src/lingxi/apps/healthcheck/__init__.py": frozenset(["D"]),
    "src/lingxi/apps/liveness.py": frozenset(["D"]),
    "src/lingxi/apps/reauthorize/__init__.py": frozenset(["D"]),
    "src/lingxi/apps/scheduler/alerting_assembly.py": frozenset(["D"]),
    "src/lingxi/apps/scheduler/assembly.py": frozenset(["D"]),
    "src/lingxi/apps/scheduler/audit.py": frozenset(["D"]),
    "src/lingxi/apps/scheduler/config.py": frozenset(["D"]),
    "src/lingxi/apps/scheduler/credential_rotation.py": frozenset(["D"]),
    "src/lingxi/apps/scheduler/daily_report.py": frozenset(["D"]),
    "src/lingxi/apps/scheduler/document_delivery_dead_letter.py": frozenset(["D"]),
    "src/lingxi/apps/scheduler/late_readiness_recovery.py": frozenset(["D", "PLR0913"]),
    "src/lingxi/apps/scheduler/loop.py": frozenset(["D"]),
    "src/lingxi/apps/scheduler/onboarding.py": frozenset(["D"]),
    "src/lingxi/apps/scheduler/org_snapshot_sync.py": frozenset(["D", "N818"]),
    "src/lingxi/apps/scheduler/permission_publish.py": frozenset(["D", "PLR0913"]),
    "src/lingxi/apps/scheduler/permission_readiness_assembly.py": frozenset(["D"]),
    "src/lingxi/apps/scheduler/permission_refresh.py": frozenset(["D", "PLR0913", "N818"]),
    "src/lingxi/apps/scheduler/retention.py": frozenset(["D"]),
    "src/lingxi/apps/scheduler/roster_audit.py": frozenset(["D"]),
    "src/lingxi/apps/scheduler/stalled_provisioning.py": frozenset(["D", "PLR0913"]),
    "src/lingxi/apps/trace/__init__.py": frozenset(["D"]),
    "src/lingxi/apps/worker/__init__.py": frozenset(["D"]),
    "src/lingxi/apps/worker/cli.py": frozenset(["D"]),
    "src/lingxi/apps/worker/config.py": frozenset(["D"]),
    "src/lingxi/apps/worker/report.py": frozenset(["D", "PLR0913"]),
    "src/lingxi/apps/worker/report_extraction.py": frozenset(["D"]),
    "src/lingxi/apps/worker/service.py": frozenset(["D", "PLR0913", "I001"]),
    "src/lingxi/apps/worker/session_cleanup.py": frozenset(["D"]),
    "src/lingxi/apps/worker/turn.py": frozenset(["D"]),
    "src/lingxi/config/content.py": frozenset(["D"]),
    "src/lingxi/core/admin/card_callback.py": frozenset(["D", "PLR0913"]),
    "src/lingxi/core/admin/card_dispatch.py": frozenset(["D", "PLR0913"]),
    "src/lingxi/core/admin/card_layout.py": frozenset(["D"]),
    "src/lingxi/core/admin/commands.py": frozenset(["D"]),
    "src/lingxi/core/admin/display_names.py": frozenset(["D"]),
    "src/lingxi/core/admin/management_card.py": frozenset(["D"]),
    "src/lingxi/core/admin/notification.py": frozenset(["D", "N818"]),
    "src/lingxi/core/admin/pending_action.py": frozenset(["D", "N818"]),
    "src/lingxi/core/admin/registry.py": frozenset(["D", "N818"]),
    "src/lingxi/core/admin/router.py": frozenset(["D", "PLR0913", "UP035"]),
    "src/lingxi/core/admin/views.py": frozenset(["D"]),
    "src/lingxi/core/alerting.py": frozenset(["D"]),
    "src/lingxi/core/conversation/commands.py": frozenset(["D"]),
    "src/lingxi/core/conversation/onboarding_recovery.py": frozenset(["D"]),
    "src/lingxi/core/conversation/pipeline.py": frozenset(["D", "PLR0913", "N818", "I001", "UP035"]),
    "src/lingxi/core/conversation/ports.py": frozenset(["D"]),
    "src/lingxi/core/conversation/session_window.py": frozenset(["D"]),
    "src/lingxi/core/daily_report.py": frozenset(["D"]),
    "src/lingxi/core/delivery/ports.py": frozenset(["D"]),
    "src/lingxi/core/execution/audit.py": frozenset(["D"]),
    "src/lingxi/core/execution/card_stream.py": frozenset(["D", "PLR0913", "N818"]),
    "src/lingxi/core/execution/document_delivery.py": frozenset(["D"]),
    "src/lingxi/core/execution/hooks.py": frozenset(["D"]),
    "src/lingxi/core/execution/input_safety.py": frozenset(["D"]),
    "src/lingxi/core/execution/message_stream.py": frozenset(["D"]),
    "src/lingxi/core/execution/tool_policy.py": frozenset(["D"]),
    "src/lingxi/core/identity/access_token_supply.py": frozenset(["D", "N818"]),
    "src/lingxi/core/identity/credentials.py": frozenset(["D", "N818"]),
    "src/lingxi/core/identity/first_contact.py": frozenset(["D"]),
    "src/lingxi/core/identity/identifiers.py": frozenset(["D"]),
    "src/lingxi/core/identity/innertest_roster_gate.py": frozenset(["D"]),
    "src/lingxi/core/identity/legacy_permission_import.py": frozenset(["D"]),
    "src/lingxi/core/identity/onboarding.py": frozenset(["D"]),
    "src/lingxi/core/identity/onboarding_guards.py": frozenset(["D"]),
    "src/lingxi/core/identity/onboarding_ports.py": frozenset(["D"]),
    "src/lingxi/core/identity/onboarding_runner.py": frozenset(["D", "PLR0913", "F401", "I001", "UP035"]),
    "src/lingxi/core/identity/onboarding_support.py": frozenset(["D"]),
    "src/lingxi/core/identity/onboarding_terminal.py": frozenset(["D", "N818"]),
    "src/lingxi/core/identity/org_snapshot.py": frozenset(["D"]),
    "src/lingxi/core/identity/preprovision.py": frozenset(["D"]),
    "src/lingxi/core/identity/provisioning.py": frozenset(["D"]),
    "src/lingxi/core/identity/roster_audit.py": frozenset(["D"]),
    "src/lingxi/core/identity/roster_report.py": frozenset(["D"]),
    "src/lingxi/core/identity/roster_snapshot.py": frozenset(["D"]),
    "src/lingxi/core/identity/stock_token_source.py": frozenset(["D"]),
    "src/lingxi/core/ids.py": frozenset(["D"]),
    "src/lingxi/core/innertest_content_capture.py": frozenset(["D"]),
    "src/lingxi/core/permission/account_match.py": frozenset(["D"]),
    "src/lingxi/core/permission/galaxy_export.py": frozenset(["D"]),
    "src/lingxi/core/permission/galaxy_scope.py": frozenset(["D"]),
    "src/lingxi/core/permission/legacy_diff.py": frozenset(["D"]),
    "src/lingxi/core/permission/local_override.py": frozenset(["D"]),
    "src/lingxi/core/permission/mcp_readiness.py": frozenset(["D"]),
    "src/lingxi/core/permission/merge_sources.py": frozenset(["D"]),
    "src/lingxi/core/permission/metric_translation.py": frozenset(["D", "N818"]),
    "src/lingxi/core/permission/notification.py": frozenset(["D"]),
    "src/lingxi/core/permission/position_override.py": frozenset(["D"]),
    "src/lingxi/core/permission/publish.py": frozenset(["D", "N818"]),
    "src/lingxi/core/permission/publish_row.py": frozenset(["D"]),
    "src/lingxi/core/permission/role_function.py": frozenset(["D"]),
    "src/lingxi/core/permission/table_access_token_supply.py": frozenset(["D", "N818"]),
    "src/lingxi/core/permission/targeted_recompute.py": frozenset(["D", "PLR0913"]),
    "src/lingxi/core/permission/tenant_token_supply.py": frozenset(["D"]),
    "src/lingxi/core/user_memory.py": frozenset(["D"]),
    "src/lingxi/core/year_grounding_guard.py": frozenset(["D"]),
    "tests/docx_body_sample.py": frozenset(["D"]),
    "tests/gateway_fakes.py": frozenset(["D"]),
    "tests/postgres_schema.py": frozenset(["D"]),
    "tests/test_acceptance_fixtures_contract.py": frozenset(["D"]),
    "tests/test_acceptance_fixtures_identity_contract.py": frozenset(["D"]),
    "tests/test_acceptance_matrix_check.py": frozenset(["D"]),
    "tests/test_admin_bootstrap_cli.py": frozenset(["D"]),
    "tests/test_admin_card_callback.py": frozenset(["D"]),
    "tests/test_admin_card_dispatch.py": frozenset(["D"]),
    "tests/test_admin_commands.py": frozenset(["D"]),
    "tests/test_admin_management_integration_postgres.py": frozenset(["D"]),
    "tests/test_admin_metric_alias_map_file.py": frozenset(["D"]),
    "tests/test_admin_metric_catalog.py": frozenset(["D"]),
    "tests/test_admin_notification.py": frozenset(["D"]),
    "tests/test_admin_position_card.py": frozenset(["D"]),
    "tests/test_admin_post_callback_executor.py": frozenset(["D"]),
    "tests/test_admin_registry.py": frozenset(["D"]),
    "tests/test_admin_registry_postgres.py": frozenset(["D"]),
    "tests/test_admin_role_full_access.py": frozenset(["D"]),
    "tests/test_admin_router.py": frozenset(["D"]),
    "tests/test_alembic_revision_check.py": frozenset(["D"]),
    "tests/test_alerting.py": frozenset(["D"]),
    "tests/test_alerting_integration.py": frozenset(["D"]),
    "tests/test_asset_gates.py": frozenset(["D"]),
    "tests/test_ci_extras_matrix.py": frozenset(["D"]),
    "tests/test_ci_layering.py": frozenset(["D"]),
    "tests/test_ci_module_manifest.py": frozenset(["D"]),
    "tests/test_claude_agent_hooks_adapter.py": frozenset(["D"]),
    "tests/test_claude_agent_session_adapter.py": frozenset(["D", "PLR0913"]),
    "tests/test_company_function_metric_map_file.py": frozenset(["D"]),
    "tests/test_content_capture_retention_duty.py": frozenset(["D"]),
    "tests/test_content_catalog.py": frozenset(["D"]),
    "tests/test_content_version_check.py": frozenset(["D"]),
    "tests/test_contract_attribution_check.py": frozenset(["D"]),
    "tests/test_conversation_commands.py": frozenset(["D"]),
    "tests/test_core_ids.py": frozenset(["D"]),
    "tests/test_core_layering_check.py": frozenset(["D"]),
    "tests/test_daily_report_duty.py": frozenset(["D"]),
    "tests/test_daily_report_render.py": frozenset(["D"]),
    "tests/test_db_timeouts.py": frozenset(["D"]),
    "tests/test_delegated_subject_lookup.py": frozenset(["D"]),
    "tests/test_delivery_outbox.py": frozenset(["D"]),
    "tests/test_deploy_checks.py": frozenset(["D"]),
    "tests/test_dev_check_gate_spec.py": frozenset(["D"]),
    "tests/test_dev_check_local_layer.py": frozenset(["D"]),
    "tests/test_document_delivery.py": frozenset(["D", "PLR0913"]),
    "tests/test_document_delivery_maintenance_duty.py": frozenset(["D"]),
    "tests/test_document_delivery_transport.py": frozenset(["D"]),
    "tests/test_docx_body_sample.py": frozenset(["D"]),
    "tests/test_epic_candidate_images.py": frozenset(["D"]),
    "tests/test_execution_tool_gate.py": frozenset(["D"]),
    "tests/test_feishu_admin_card_payload.py": frozenset(["D"]),
    "tests/test_feishu_admin_card_transport.py": frozenset(["D"]),
    "tests/test_feishu_bitable_org_association.py": frozenset(["D"]),
    "tests/test_feishu_card_action_event.py": frozenset(["D"]),
    "tests/test_feishu_delivery_card_payload.py": frozenset(["D"]),
    "tests/test_feishu_delivery_classification.py": frozenset(["D"]),
    "tests/test_feishu_directory_adapter.py": frozenset(["D"]),
    "tests/test_feishu_docx_delivery.py": frozenset(["D"]),
    "tests/test_feishu_org_snapshot_reader.py": frozenset(["D"]),
    "tests/test_feishu_reauthorization.py": frozenset(["D"]),
    "tests/test_feishu_roster_bitable.py": frozenset(["D"]),
    "tests/test_feishu_roster_reader.py": frozenset(["D"]),
    "tests/test_feishu_sheets_delivery.py": frozenset(["D"]),
    "tests/test_feishu_tenant_token.py": frozenset(["D"]),
    "tests/test_feishu_user_message.py": frozenset(["D"]),
    "tests/test_galaxy_account_match.py": frozenset(["D"]),
    "tests/test_galaxy_csv_export.py": frozenset(["D"]),
    "tests/test_galaxy_export_validation.py": frozenset(["D"]),
    "tests/test_galaxy_import_postgres.py": frozenset(["D"]),
    "tests/test_galaxy_import_script.py": frozenset(["D"]),
    "tests/test_galaxy_role_function.py": frozenset(["D"]),
    "tests/test_galaxy_scope_join.py": frozenset(["D"]),
    "tests/test_gateway_config.py": frozenset(["D"]),
    "tests/test_gateway_delivery.py": frozenset(["D"]),
    "tests/test_gateway_delivery_resilience.py": frozenset(["D"]),
    "tests/test_gateway_log_redaction.py": frozenset(["D"]),
    "tests/test_gateway_longconn.py": frozenset(["D"]),
    "tests/test_gateway_onboarding_recovery.py": frozenset(["D"]),
    "tests/test_gateway_pipeline.py": frozenset(["D"]),
    "tests/test_gateway_pipeline_admin.py": frozenset(["D"]),
    "tests/test_gateway_postgres.py": frozenset(["D"]),
    "tests/test_gateway_process.py": frozenset(["D"]),
    "tests/test_gateway_transport.py": frozenset(["D", "N818"]),
    "tests/test_host_health_alert_script.py": frozenset(["D"]),
    "tests/test_identity_credentials.py": frozenset(["D"]),
    "tests/test_identity_first_contact.py": frozenset(["D"]),
    "tests/test_identity_org_snapshot.py": frozenset(["D"]),
    "tests/test_identity_postgres_records.py": frozenset(["D"]),
    "tests/test_identity_provisioning_contract.py": frozenset(["D"]),
    "tests/test_import_local_permission_override.py": frozenset(["D"]),
    "tests/test_import_local_permission_override_postgres.py": frozenset(["D"]),
    "tests/test_innertest_content_capture.py": frozenset(["D"]),
    "tests/test_innertest_roster_gate.py": frozenset(["D"]),
    "tests/test_input_safety.py": frozenset(["D"]),
    "tests/test_invalidate_pretranslation_publish_intents_script.py": frozenset(["D"]),
    "tests/test_late_readiness_recovery.py": frozenset(["D"]),
    "tests/test_liveness_and_healthcheck.py": frozenset(["D"]),
    "tests/test_local_override.py": frozenset(["D"]),
    "tests/test_local_permission_postgres.py": frozenset(["D"]),
    "tests/test_log_exception_body_leak.py": frozenset(["D"]),
    "tests/test_management_card.py": frozenset(["D", "N802"]),
    "tests/test_management_correction.py": frozenset(["D"]),
    "tests/test_matrix_row_size_ratchet_check.py": frozenset(["D"]),
    "tests/test_mcp_readiness_machine.py": frozenset(["D"]),
    "tests/test_mcp_token_cipher.py": frozenset(["D"]),
    "tests/test_mcp_token_postgres.py": frozenset(["D"]),
    "tests/test_metric_map_single_source.py": frozenset(["D", "N818"]),
    "tests/test_onboarding.py": frozenset(["D"]),
    "tests/test_onboarding_runner.py": frozenset(["D"]),
    "tests/test_ops_log_retention.py": frozenset(["D"]),
    "tests/test_pending_action.py": frozenset(["D"]),
    "tests/test_pending_action_postgres.py": frozenset(["D"]),
    "tests/test_permission_bitable_adapter.py": frozenset(["D"]),
    "tests/test_permission_legacy_diff.py": frozenset(["D"]),
    "tests/test_permission_merge_sources.py": frozenset(["D"]),
    "tests/test_permission_metric_translation.py": frozenset(["D"]),
    "tests/test_permission_notification.py": frozenset(["D"]),
    "tests/test_permission_publish_duty.py": frozenset(["D", "PLR0913"]),
    "tests/test_permission_publish_executor.py": frozenset(["D"]),
    "tests/test_permission_publish_postgres.py": frozenset(["D", "N818"]),
    "tests/test_permission_publish_row.py": frozenset(["D", "N802"]),
    "tests/test_permission_recompute_trigger.py": frozenset(["D"]),
    "tests/test_permission_recompute_trigger_postgres.py": frozenset(["D"]),
    "tests/test_permission_refresh_duty.py": frozenset(["D", "PLR0913"]),
    "tests/test_permission_refresh_postgres.py": frozenset(["D"]),
    "tests/test_permission_retention_duty.py": frozenset(["D"]),
    "tests/test_permission_table_access_token_supply.py": frozenset(["D"]),
    "tests/test_polling_connection_reuse_wiring.py": frozenset(["D"]),
    "tests/test_postgres_connection_reuse.py": frozenset(["D"]),
    "tests/test_postgres_content_capture.py": frozenset(["D"]),
    "tests/test_postgres_daily_report.py": frozenset(["D"]),
    "tests/test_postgres_daily_report_watermark.py": frozenset(["D"]),
    "tests/test_postgres_isolation_contract.py": frozenset(["D"]),
    "tests/test_postgres_late_readiness_recovery.py": frozenset(["D"]),
    "tests/test_postgres_onboarding_failure.py": frozenset(["D"]),
    "tests/test_postgres_schema_fixture.py": frozenset(["D"]),
    "tests/test_postgres_stalled_provisioning.py": frozenset(["D"]),
    "tests/test_postgres_user_memory.py": frozenset(["D"]),
    "tests/test_preprovision.py": frozenset(["D"]),
    "tests/test_preprovision_ops.py": frozenset(["D"]),
    "tests/test_probe_drive_folder_permissions.py": frozenset(["D"]),
    "tests/test_probe_message_reactions_script.py": frozenset(["D"]),
    "tests/test_query_mcp_probe.py": frozenset(["D"]),
    "tests/test_queue_connection_reuse.py": frozenset(["D"]),
    "tests/test_reauthorize_app.py": frozenset(["D"]),
    "tests/test_replay_inbound_event_script.py": frozenset(["D"]),
    "tests/test_resource_sample_helper.py": frozenset(["D"]),
    "tests/test_retention_postgres.py": frozenset(["D"]),
    "tests/test_roster_access_token_supply.py": frozenset(["D", "PLR0913", "N818"]),
    "tests/test_roster_audit_diff.py": frozenset(["D"]),
    "tests/test_roster_audit_duty.py": frozenset(["D"]),
    "tests/test_roster_audit_postgres.py": frozenset(["D"]),
    "tests/test_roster_daily_report.py": frozenset(["D"]),
    "tests/test_roster_daily_source.py": frozenset(["D"]),
    "tests/test_roster_snapshot.py": frozenset(["D"]),
    "tests/test_roster_snapshot_postgres.py": frozenset(["D"]),
    "tests/test_roster_snapshot_sync_duty.py": frozenset(["D"]),
    "tests/test_scheduler_audit.py": frozenset(["D"]),
    "tests/test_scheduler_daily_report_assembly.py": frozenset(["D"]),
    "tests/test_scheduler_onboarding_assembly.py": frozenset(["D"]),
    "tests/test_scheduler_org_snapshot_assembly.py": frozenset(["D"]),
    "tests/test_scheduler_org_snapshot_sync.py": frozenset(["D"]),
    "tests/test_scheduler_process.py": frozenset(["D"]),
    "tests/test_sheet_delivery_transport.py": frozenset(["D"]),
    "tests/test_size_ratchet_check.py": frozenset(["D"]),
    "tests/test_stalled_provisioning.py": frozenset(["D"]),
    "tests/test_stock_token_bitable.py": frozenset(["D"]),
    "tests/test_targeted_permission_recompute.py": frozenset(["D", "PLR0913"]),
    "tests/test_tenant_token_supply.py": frozenset(["D"]),
    "tests/test_tool_policy_redirect.py": frozenset(["D"]),
    "tests/test_trace_cli.py": frozenset(["D"]),
    "tests/test_user_environment.py": frozenset(["D"]),
    "tests/test_user_mcp_config.py": frozenset(["D"]),
    "tests/test_user_memory.py": frozenset(["D"]),
    "tests/test_worker_content_capture_config.py": frozenset(["D"]),
    "tests/test_worker_entry.py": frozenset(["D", "PLR0913"]),
    "tests/test_worker_env_inheritance.py": frozenset(["D"]),
    "tests/test_worker_listener_recovery.py": frozenset(["D"]),
    "tests/test_worker_process.py": frozenset(["D"]),
    "tests/test_worker_queue_consumer.py": frozenset(["D"]),
    "tests/test_worker_session_cleanup.py": frozenset(["D"]),
    "tests/test_worker_user_env_root_precheck.py": frozenset(["D"]),
    "tests/test_worker_user_memory.py": frozenset(["D"]),
    "tests/test_worker_workspace_precheck.py": frozenset(["D"]),
    "tests/test_year_grounding_guard.py": frozenset(["D"]),
}

# 门禁接线批不写 [tool.ruff.format]，exclude 就是空集；全仓格式化批接线时这条
# 常量需要同步换成它实际写入的排除列表。
PINNED_FORMAT_EXCLUDE: frozenset[str] = frozenset()


class PerFileIgnoresOnlyShrinksTest(unittest.TestCase):
    """per-file-ignores 只许变短：新文件、新规则码都判红。"""

    def test_every_registered_file_is_within_the_pinned_set(self) -> None:
        """登记表里出现钉住快照没有的新文件即判红。"""
        actual = _load_ruff_config()["lint"]["per-file-ignores"]
        unpinned_files = sorted(set(actual) - set(PINNED_PER_FILE_IGNORES))
        self.assertEqual(
            unpinned_files,
            [],
            f"per-file-ignores 出现钉住快照里没有的新文件：{unpinned_files}——"
            "只允许删除或缩短既有条目，新增文件视为门禁被放宽，须先更新本文件的"
            "钉住快照并说明理由。",
        )

    def test_every_registered_codes_list_is_within_the_pinned_codes(self) -> None:
        """某个文件的豁免码里出现钉住快照没有的新码即判红。"""
        actual = _load_ruff_config()["lint"]["per-file-ignores"]
        overflowing: dict[str, list[str]] = {}
        for path, codes in actual.items():
            pinned_codes = PINNED_PER_FILE_IGNORES.get(path, frozenset())
            extra = sorted(set(codes) - pinned_codes)
            if extra:
                overflowing[path] = extra
        self.assertEqual(
            overflowing,
            {},
            f"以下文件的 per-file-ignores 出现钉住快照里没有的新规则码：{overflowing}"
            "——只允许收紧（删码），新增规则码视为门禁被放宽。",
        )

    def test_pinned_snapshot_itself_is_not_accidentally_empty(self) -> None:
        """自证：钉住快照本身不能是空字典。

        空字典会让两条子集断言永远空判通过，起不到钉住的作用——防止本文件被后续改动
        悄悄改成永远绿的空壳。
        """
        self.assertGreater(len(PINNED_PER_FILE_IGNORES), 0)


class FormatExcludeOnlyShrinksTest(unittest.TestCase):
    """format.exclude 只许变短；本批是空集，全仓格式化批接线后同步更新钉住快照。"""

    def test_format_exclude_is_within_the_pinned_set(self) -> None:
        """format.exclude 出现钉住快照没有的新条目即判红。"""
        format_section = _load_ruff_config().get("format", {})
        actual = frozenset(format_section.get("exclude", []))
        extra = sorted(actual - PINNED_FORMAT_EXCLUDE)
        self.assertEqual(
            extra,
            [],
            f"format.exclude 出现钉住快照里没有的新条目：{extra}——只允许收紧。",
        )


if __name__ == "__main__":
    unittest.main()
